### ISSUE TITLE
howto define a shotcut for the backspace key ?

### ISSUE THREAD

**Issue by evantill** [triplus/ShortCuts#5]
On a french keyboard I have no _DEL_ key but I have _BACKSPACE_ key.

I would like to use the _BACKSPACE_ key for the delete action. How should I define it in the shortcut panel ?

**Comment by triplus** [comment]
This should do (replace the Del string with Backspace string):

![backspace](https://user-images.githubusercontent.com/2895019/51865747-82770880-2347-11e9-8daa-5aed33b8a286.png)

**Comment by triplus** [comment]
Just wondering did the suggestion work?

**Comment by evantill** [comment]
Yes thank you. Using `Backspace` as a shortcut work. 👍

**Comment by evantill** [comment]
as a side note on mac 

> the combination Fn-Backspace acts like a normal delete key

see https://discussions.apple.com/thread/495913
